cart/urls.py
from django.urls import path
from .views import add_to_cart, cart_detail, cart_remove_item, delete_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>', cart_remove_item, name='cart_remove_item'),
    path('delete/<int:product_id>', delete_cart_item, name='delete_cart_item')
]

kaswar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views as shop_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', shop_views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('account/create/', shop_views.signupView, name='signup')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

shop/urls.py
from django.urls import path
from .views import allProducts, productDetails


app_name='shop'

urlpatterns = [
    path('', allProducts, name="allProducts"),
    path('<slug:category_slug>/', allProducts, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', productDetails, name='productDetails')
]

cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date_added']
    

    def __str__(self):
        return str(self.cart_id)

    def __unicode__(self):
        return str(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    def sub_total(self):
        return self.quantity * self.product.price
    

    def __str__(self):
        return self.product

    def __unicode__(self):
        return self.product

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product, UserShippingDetail
from .models import Cart, CartItem
from order.models import Order, OrderItem
from django.conf import settings
from django.contrib.auth.models import User
import uuid

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity <= cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, cart=cart, quantity=1)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter =+ cart_item.quantity
    except Exception:
        pass
    
    paystack_data_key = settings.PAYSTACK_PUBLISHABLE_KEY
    transaction_id = uuid.uuid4()
    paystack_total = total * 100

    #Creating the order
    user = User.objects.get(username=request.user.username)
    print('User is: ',user)
    customer_datails = UserShippingDetail.objects.get(user=user)
    if request.method == 'POST':
        order = Order.objects.create(transaction_id=transaction_id, total=total, email=request.user.email, shippingName=request.user.first_name+' '+request.user.last_name, shippingAddress=customer_datails.shippingAddress, shippingCity=customer_datails.shippingCity)
        order.save()
        for item in cart_items:
            order_item = OrderItem.objects.create(order=order, product=item.product.name, quantity=item.quantity, price=item.product.price)
            order_item.save()

            product = Product.objects.get(id=item.product.id)
            product.stock = int(item.product.stock - item.quantity)
            product.save()
            item.delete()
        return redirect('shop:allProducts')
        
    return render(request, 'cart/cart_detail.html', {'cart_items':cart_items, 'total':total, 'counter':counter, 'paystack_data_key':paystack_data_key, 'transaction_id':transaction_id, 'paystack_total':paystack_total})


def cart_remove_item(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def delete_cart_item(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends 'base.html' %} {% load static %} {% block body %}
<main class="page">
    <section class="shopping-cart dark">
        <div class="container">
            <div class="block-heading">
                <h2>Shopping Cart</h2>
                <p>Review your cart and proceed to payment or continue shopping. You will need an account with us to keep track of your orders history.</p>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="items">
                            {% if cart_items %} {% for cart_item in cart_items %}
                            <div class="product">
                                <div class="row">
                                    <div class="col-md-3">
                                        <img class="img-fluid mx-auto d-block image" src="{{cart_item.product.image.url}}">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="info">
                                            <div class="row">
                                                <div class="col-md-5 product-name">
                                                    <div class="product-name">
                                                        <a href="{{cart_item.product.get_absolute_url}}">{{cart_item.product.name}}</a>
                                                        <div class="product-info">
                                                            <div>
                                                                <a href="{% url 'cart:add_to_cart'  product_id=cart_item.product.id %}" class="btn btn-success"><i class="fas fa-plus-square"></i></a>
                                                                <a href="{% url 'cart:cart_remove_item'  product_id=cart_item.product.id %}" class="btn btn-warning"><i class="fas fa-minus-square"></i></a>
                                                                <a href="{% url 'cart:delete_cart_item'  product_id=cart_item.product.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-4 quantity">
                                                    <label for="quantity">Quantity:</label>
                                                    <input id="quantity" type="number" value="{{cart_item.quantity}}" class="form-control quantity-input" disabled>
                                                   
                                                </div>
                                                <div class="col-md-3 price">
                                                    <span> x ${{cart_item.product.price}}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %} {% else %}
                            <h3>Not item in cart</h3>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-4">
                        <div class="summary">
                            <h3>Summary</h3>
                            <div class="summary-item">
                                <span class="text">Discount</span>
                                <span class="price">$0</span>
                            </div>
                            <div class="summary-item">
                                <span class="text">Shipping</span>
                                <span class="price">$0</span>
                            </div>
                            <div class="summary-item">
                                <span class="text">Total</span>
                                <span class="price">${{total}}</span>
                            </div>
                            <div>
                                <a href="{% url 'shop:allProducts' %}" class="btn btn-primary btn-lg btn-block">Continue shopping</a>
                                {% if user.is_authenticated %}
                                <form action="" method="POST" >
                                        {% csrf_token %}
                                        <script
                                            src="https://js.paystack.co/v1/inline.js" 
                                            data-key="{{ paystack_data_key }}"
                                            data-email="customer@email.com"
                                            data-amount="{{paystack_total}}"
                                            data-ref="{{ transaction_id }}"
                                        >
                                        </script>
                                    </form>
                                {% else %}
                                <a href="{% url 'signup' %}" class="btn btn-primary btn-lg btn-block">Register to process your order</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock body %}