cart/urls.py
from django.urls import path
from .views import add_to_cart, cart_detail, cart_remove_item, delete_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>', cart_remove_item, name='cart_remove_item'),
    path('delete/<int:product_id>', delete_cart_item, name='delete_cart_item')
]

kaswar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views as shop_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', shop_views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('account/create/', shop_views.signupView, name='signup')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

search_app/urls.py
from django.urls import path
from .views import searchResult

app_name = 'search_app'

urlpatterns = [
    path('', searchResult, name='searchResult')
]

shop/urls.py
from django.urls import path
from .views import allProducts, productDetails


app_name='shop'

urlpatterns = [
    path('', allProducts, name="allProducts"),
    path('<slug:category_slug>/', allProducts, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', productDetails, name='productDetails')
]

templates/includes/carousel.html
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

templates/includes/category_menu.html
<div class="list-group">
    {% for link in category_links %}
        <a href="{{ link.get_absolute_url }}" class="list-group-item">{{link.name}}</a>
    {% endfor %}
</div>

templates/includes/footer.html
<div>
    <p>&copy; Kaswar.com All rights reserved</p>
</div>

templates/includes/header.html
{% load static %}
<header>
    <center>
        <img src="{% static 'img/kaswar_logo.png' %}" alt="Perfect Cushion Store">
    </center>
</header>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'shop:allProducts' %}">Shop
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
                </li>

            </ul>
            <form class="form-inline mt-2 mt-md-0" action="{% url 'search_app:searchResult' %}" method="GET">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name='q'>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div>
    </div>
</nav>